apiVersion: builtin
kind: SecretGenerator
metadata:
  name: sas-consul-config
behavior: merge
literals:
  - INGRESS_HOST={{ V4_CFG_INGRESS_FQDN }}
files:
  - SITEDEFAULT_CONF=site-config/sitedefault.yaml
{% if V4MT_ENABLE == true %}
  - SASDEFAULT_CONF=site-config/multi-tenant/sasdefault.yaml
{% endif %}
